# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 980a731654d81c7462cf17a504ccf985db94a7c23bf5d9e51bfbf566a4d5a76fa4925bf8d35eae3109371585d19dd2b5409ba3b3844e8c75c0f166384eb54a2d

test:
  secret_key_base: 1b404950fa724575ca4a3aabff74d68e362a9fd0eee5e6c0273322e9a6b020028525b62ec355baf1623ae2529ee4cc15afb3a1f22eea411784c2d50967f75d6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
